//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace L06_Task01
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Pages { get; set; }
        public int AuthorsId { get; set; }
        public int LanguagesId { get; set; }
    
        public virtual Authors Authors { get; set; }
        public virtual Languages Languages { get; set; }
    }
}
